services:
  jupyter:
    build: .
    image: matplotlibmasterpro
    command: jupyter
    ports: ["8888:8888"]
    volumes:
      - ./notebooks:/app/notebooks
      - ./exports:/app/exports
      - ./datasets:/app/datasets

  streamlit:
    build: .
    image: matplotlibmasterpro
    command: streamlit
    ports: ["8501:8501"]
    volumes:
      - ./exports:/app/exports:ro

  test:
    build: .
    image: matplotlibmasterpro
    command: test
    profiles: ["ci"]
