#!/usr/bin/env python3
"""
Generate ``docs/API.md`` from the public API of every ``mplmasterpro`` module.

Each module's ``__all__`` defines what is public. For every function the
signature and the first paragraph of its docstring are emitted; constants get
their type and length. Run after changing any public signature::

    python scripts/generate_api_docs.py
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import mplmasterpro
from mplmasterpro import colors, datasets, plot_utils, publication, stats, theme_utils

MODULES = [publication, stats, colors, theme_utils, plot_utils, datasets]
OUT = ROOT / "docs" / "API.md"
_ABBREVIATIONS = [
    ("collections.abc.", ""),
    ("matplotlib.axes._axes.Axes", "Axes"),
    ("matplotlib.figure.Figure", "Figure"),
    ("matplotlib.animation.FuncAnimation", "FuncAnimation"),
    ("pandas.core.frame.DataFrame", "pd.DataFrame"),
    ("pandas.core.series.Series", "pd.Series"),
    ("numpy.random._generator.Generator", "np.random.Generator"),
    ("numpy.ndarray", "np.ndarray"),
    ("typing.", ""),
    ("pathlib.Path", "Path"),
]


def first_paragraph(doc: str | None) -> str:
    if not doc:
        return "_No docstring._"
    lines = inspect.cleandoc(doc).splitlines()
    para: list[str] = []
    for line in lines:
        if not line.strip():
            if para:
                break
            continue
        para.append(line.strip())
    return " ".join(para)


def format_signature(obj) -> str:
    try:
        sig = str(inspect.signature(obj, eval_str=True))
    except (TypeError, ValueError):
        return "(...)"
    for long, short in _ABBREVIATIONS:
        sig = sig.replace(long, short)
    return sig.replace("NoneType", "None")


def render_module(module) -> str:
    name = module.__name__
    out = [f"## `{name}`", "", first_paragraph(module.__doc__), ""]
    functions, constants = [], []
    for item in getattr(module, "__all__", []):
        obj = getattr(module, item)
        (functions if callable(obj) else constants).append((item, obj))
    if constants:
        out.append("### Constants")
        out.append("")
        out.append("| Name | Type | Notes |")
        out.append("| --- | --- | --- |")
        for item, obj in constants:
            size = f"{len(obj)} entries" if hasattr(obj, "__len__") else repr(obj)
            out.append(f"| `{item}` | `{type(obj).__name__}` | {size} |")
        out.append("")
    if functions:
        out.append("### Functions")
        out.append("")
        for item, obj in functions:
            out.append(f"#### `{item}`")
            out.append("")
            out.append("```python")
            out.append(f"{item}{format_signature(obj)}")
            out.append("```")
            out.append("")
            out.append(first_paragraph(obj.__doc__))
            out.append("")
    return "\n".join(out)


def main() -> int:
    parts = [
        "# API reference",
        "",
        f"`mplmasterpro` {mplmasterpro.__version__}. Generated by `scripts/generate_api_docs.py`; "
        "do not edit by hand.",
        "",
        "Top-level re-exports: "
        + ", ".join(
            f"`{n}`"
            for n in mplmasterpro.__all__
            if not n.startswith("__")
            and n not in {"colors", "datasets", "plot_utils", "publication", "stats", "theme_utils"}
        ),
        "",
        "Modules: " + ", ".join(f"[`{m.__name__}`](#{m.__name__.replace('.', '')})" for m in MODULES),
        "",
    ]
    parts.extend(render_module(m) for m in MODULES)
    OUT.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
